---
- name: Calculator MiniProject
  hosts: localhost
  remote_user: SAMARJEET
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "samnotlazy/my-app:latest"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Running Container
      shell: docker run -it -d --name=my-app samnotlazy/my-app